### ISSUE TITLE
Windows defender error while compiling the app

### ISSUE THREAD

**Issue by chigivigi** [kine/navertical_tasks#11]
I have successfully created a container and I am currently trying to compile the app inside it using the CompileBCApps task.
For authentication I am using NavUserPassword and a random username and password for both create container and compiling the app.

The compile process runs for about 15 minutes and then throws the error:
Access to the path 'C:\Program Files\Windows Defender Advanced Threat Protection\Classification\Configuration' is denied.

This are my compile app parameters:
- task: CompileBCApps@2
  inputs:
    ContainerName: 'test'
    RepoPath: '/'
    EnableCop: false
    EnableAppsourceCop: false
    EnableUICop: false
    FailOn: 'warning'
    auth: 'NavUserPassword'
    username: 'x'
    password: 'y'

**Comment by kine** [comment]
Hi,
This issue will not be anyhow connected to the navertical tasks. I think it will be connected to docker. 

Are you using your own Agent or you are using Microsoft hosted agent?

**Comment by chigivigi** [comment]
We are using a Azure pipeline hosted agent with a wmImage windows-2019.
It is a requirement in our case description.

**Comment by kine** [comment]
Seems that the params are not correct. I think that you do not have the repo to compile in root folder ('/'). You need to use system variables to set the correct path. I am using this:
```
  - task: CompileBCApps@2
    displayName: Compile Apps
    inputs:
      ContainerName: ${{ parameters.ContainerName }}
      RepoPath: '$(Build.SourcesDirectory)'
      FailOn: 'error'
      Auth: ${{ parameters.Auth }}
      Username: ${{ parameters.Username }}
      Password: ${{ parameters.Password }}
      EnableCop: ${{ parameters.EnableCop }}
      EnableAppsourceCop: ${{ parameters.EnableAppsourceCop }}
      EnablePerTenantExtensionCop: ${{ parameters.EnablePerTenantExtensionCop }}
      EnableUICop: ${{ parameters.EnableUICop }}
      RulesetFile: ${{ parameters.RulesetFile }}
      AsmProbingPaths: ${{ parameters.AsmProbingPaths }}
```
This is part of my yaml template, thus I am using the "parameters." things to set the values. But for you the '$(Build.SourcesDirectory)' is what should interests you. Because if you use /, the process will search through your whole disc for app.json files and it means that it tries to touch the mentioned folder where it have no permissions.
