### ISSUE TITLE
signappTask install error

### ISSUE THREAD

**Issue by walkerjono** [kine/navertical_tasks#13]
I'm trying to use the standard signappTask action within Azure DevOps YAML pipeline to sign a BC extension with an Azure Keyvault certificate, using a hosted agent, configured as:

```yaml
  - task: signbcapp@3
    displayName: Sign App
    condition: and(succeeded(), eq(variables['hasIsvObjectRange'], 'true'))
    inputs:
      skiptoolinstall: false
      keyvaultname: $(keyvault-name)
      keyvaultcertificatename: $(keyvault-certificatename)
      clientid: $(keyvault-clientid)
      tenantid: $(keyvault-tenantid)
      clientsecret: $(keyvault-clientsecret)
      appfile: $(SourceFileName)
```

when running I get the following error:

```log
Starting: Sign App
==============================================================================
Task         : Business Central - Sign App with certificate through Container
Description  : Sign App for Dynamics 365 Business Central with usage of container
Version      : 3.4.0
Author       : Kine
Help         : 
==============================================================================
Using KeyVault <name> for signing the files
Installing dotnet tool
dotnet-install: Remote file https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.408/dotnet-sdk-8.0.408-win-x64.zip size is 281538746 bytes.
dotnet-install: Downloaded file https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.408/dotnet-sdk-8.0.408-win-x64.zip size is 281538746 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "C:\Users\VssAdministrator\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not ensure your Windows version is supported during the installation.
dotnet-install: To check the list of supported versions, go to https://learn.microsoft.com/dotnet/core/install/windows#supported-versions
dotnet-install: Installed version is 8.0.408
dotnet-install: Installation finished
Installation of dotnet tool complete
Signing these files:
Using Entra app to authenticate
Importing module NVRAppDevOps
BcContainerHelper version 6.1.4
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.20348.2849
WARNING: The names of some imported commands from the module 'BcContainerHelper' include unapproved verbs that might 
make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the 
Verbose parameter. For a list of approved verbs, type Get-Verb.
NVRAppDevOps version 2.8.3 
##[error]The term 'Install-SigningTool' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Finishing: Sign App
```

I've also tried manually installing https://github.com/kine/NVRAppDevOps/blob/master/NVRAppDevOps/Install-SigningTool.ps1 directly after `NVRAppDevOps` :

```yaml
  # Install the NVRAppDevOps PowerShell module
  # https://github.com/kine/NVRAppDevOps
  # https://github.com/kine/navertical_tasks
  - task: InstallBCModules@3
    displayName: Install NVRAppDevOps
    inputs:
      UninstallOldVersions: false
      allowPreRelease: ${{ parameters.isBcPublicPreview }}
      # allowPreRelease: true

  - task: PowerShell@2
    displayName: Install signing tool - PS
    condition: and(succeeded(), eq(variables['hasIsvObjectRange'], 'true'))
    inputs:
      targetType: inline
      script: |
      
        Write-Host "Start Install SigningTool"
        
        Install-SigningTool
        
        Write-Host "End Install SigningTool"
```

But this also fails:

```log
Starting: Install signing tool - PS
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.247.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\0eefa884-3261-4606-b7b8-08d7b04a6069.ps1'"
Start Install SigningTool
Install-SigningTool : The term 'Install-SigningTool' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At D:\a\_temp\0eefa884-3261-4606-b7b8-08d7b04a6069.ps1:6 char:1
+ Install-SigningTool
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-SigningTool:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
##[error]PowerShell exited with code '1'.
Finishing: Install signing tool - PS

```

Any assistance, direction or workarounds would be greatly appreciated
